### PR TITLE
Initial Intercom widget

### PR DESCRIPTION
**Pull request by erickpintor**
Closes: https://github.com/faunadb/sales-engineering/issues/460, https://github.com/faunadb/dashboard/issues/17

I'm still faking user auth through local storage api for now. There is a small styling issue that is causing the chat bubble to appear on top of the repl. I'll fix that in a another PR.

### CODE REVIEW

**Comment by marrony** [comment]
Did you make the widget render on the page? I tried to fake a `CloudUser` with my settings but I got an error on intercom side.

```
{"type":"error.list","request_id":"apiahfoo9jp6l07ln1hg","errors":[{"code":"signature_mismatch","message":"Incorrect user_hash"}]}
```

Where did you find the `user_hash`?

**Comment by erickpintor** [comment]
You have to login on the website and then look at `window.intercomSettings`. There you will find your id, email, and `user_hash`.

**Comment by marrony** [comment]
```json
{"type":"error.list","request_id":null,"errors":[{"code":"403","message":"This domain has not been whitelisted for the Intercom app defined in the JavaScript snippet."}]}
```

now I got this error. I search for this and there is an option on intercom to whitelisting domains, but it say:

> The Intercom Messenger will only appear on these domains. If you leave this field blank, the Messenger can be added to any domain.

and the field is blank

**Comment by erickpintor** [comment]
Let me send you my script in private.

**Comment by marrony** [comment]
Can we merge this PR?

**Comment by erickpintor** [comment]
Merging.

**Pull request merged**
