### PR TITLE
Persist secret and endpoint

### PR DESCRIPTION
**Pull request by erickpintor**
Just so we can refresh the page without losing the previous connection.

### CODE REVIEW

**Comment by erickpintor** [comment]
This will be refactored and better tested as part of my next task: https://github.com/faunadb/sales-engineering/issues/460

**Comment by erickpintor** [comment]
I'm sorry. @marrony can you review the last commit. I didn't realise you have reviewed this already.

**Comment by marrony** [comment]
I see your last commit. I wonder if the original idea was to save auth data only in the development mode? Or have you changed your mind?

**Comment by erickpintor** [comment]
I did change my mind after last meeting. Until we have a proper auth mechanism in place, I think this is too insecure. Even for a alpha product.

**Pull request merged**
