### PR TITLE
Repl improvements

### PR DESCRIPTION
**Pull request by erickpintor**
Closes: https://github.com/faunadb/dashboard/issues/98

### CODE REVIEW

**Comment by jchris** [comment]
Code looks good to me, I'm wanting to merge a full round of stuff to master before I do acceptance testing. I added this line to the acceptance test script:

* clear the text area and write `q.` to trigger tag completion and ensure the Fauna query API is available

**Comment by jchris** [comment]
I'm running through an acceptance pass now with everything we've merged today plus this. If it passes I'll go ahead and merge this.

**Comment by jchris** [comment]
This isn't working, I get errors like 
```
[ReferenceError: q is not defined]
```

for the default query. Maybe q has to be an argument to the `replEval` function?

**Comment by jchris** [comment]
here is how eval used to look https://github.com/faunadb/dashboard/blob/dc9e8e27e56f116d35b30c16719c8cb8cb469a32/src/fauna-repl/repl/repl-eval.js

**Comment by erickpintor** [comment]
It has stoped to work after I've rebased with master. I have no idea why.

Anyway, I was thinking about this while running this evening. I think removing the `q.` was a bad move since people won't be able to copy and past their queries from the dashboard to their application.

I've improved the autocomplete to consider `q.` a prefix when showing query language functions.

**Comment by erickpintor** [comment]
JS `eval` is context aware. If you do `eval("q.Get(q.Ref("some-ref"))")`, for example, it needs the `q` variable in scope.

I was using `import { query as q } from "faunadb"`, which was having the same effect but it stoped to work after I've rebased the branch with master.

**Comment by marrony** [comment]
🐑 it

**Pull request merged**
